sudo: required
services:
  - docker

before_install:
  - docker build -t abhishekb-devmanager/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true abhishekb-devmanager/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-759759588288"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY